let css = "";
css +=
  "@import url(http://fonts.googleapis.com/css?family=Open+Sans|Roboto+Slab);";
css += "";
css += "/* http://meyerweb.com/eric/tools/css/reset/ ";
css += "   v2.0 | 20110126";
css += "   License: none (public domain)";
css += "*/";
css += "";
css += "html,";
css += "body,";
css += "div,";
css += "span,";
css += "applet,";
css += "object,";
css += "iframe,";
css += "h1,";
css += "h2,";
css += "h3,";
css += "h4,";
css += "h5,";
css += "h6,";
css += "p,";
css += "blockquote,";
css += "pre,";
css += "a,";
css += "abbr,";
css += "acronym,";
css += "address,";
css += "big,";
css += "cite,";
css += "code,";
css += "del,";
css += "dfn,";
css += "em,";
css += "img,";
css += "ins,";
css += "kbd,";
css += "q,";
css += "s,";
css += "samp,";
css += "small,";
css += "strike,";
css += "strong,";
css += "sub,";
css += "sup,";
css += "tt,";
css += "var,";
css += "b,";
css += "u,";
css += "i,";
css += "center,";
css += "dl,";
css += "dt,";
css += "dd,";
css += "ol,";
css += "ul,";
css += "li,";
css += "fieldset,";
css += "form,";
css += "label,";
css += "legend,";
css += "table,";
css += "caption,";
css += "tbody,";
css += "tfoot,";
css += "thead,";
css += "tr,";
css += "th,";
css += "td,";
css += "article,";
css += "aside,";
css += "canvas,";
css += "details,";
css += "embed,";
css += "figure,";
css += "figcaption,";
css += "footer,";
css += "header,";
css += "hgroup,";
css += "menu,";
css += "nav,";
css += "output,";
css += "ruby,";
css += "section,";
css += "summary,";
css += "time,";
css += "mark,";
css += "audio,";
css += "video {";
css += "  margin: 0;";
css += "  padding: 0;";
css += "  border: 0;";
css += "  font-size: 100%;";
css += "  font: inherit;";
css += "  vertical-align: baseline;";
css += "}";
css += "/* HTML5 display-role reset for older browsers */";
css += "article,";
css += "aside,";
css += "details,";
css += "figcaption,";
css += "figure,";
css += "footer,";
css += "header,";
css += "hgroup,";
css += "menu,";
css += "nav,";
css += "section {";
css += "  display: block;";
css += "}";
css += "body {";
css += "  line-height: 1;";
css += "}";
css += "ol,";
css += "ul {";
css += "  list-style: none;";
css += "}";
css += "blockquote,";
css += "q {";
css += "  quotes: none;";
css += "}";
css += "blockquote:before,";
css += "blockquote:after,";
css += "q:before,";
css += "q:after {";
css += '  content: "";';
css += "  content: none;";
css += "}";
css += "table {";
css += "  border-collapse: collapse;";
css += "  border-spacing: 0;";
css += "}";
css += "";
css += "/* STYLES */";
css += "";
css += "body {";
css += "  background-color: #3f3f4e;";
css += '  font-family: "Open Sans", "Helvetica", sans-serif;';
css += "  padding: 50px;";
css += "  max-width: 500px;";
css += "  margin: auto;";
css += "}";
css += "";
css += "h1,";
css += "h2,";
css += "h3,";
css += "h4,";
css += "h5,";
css += "h6 {";
css += '  font-family: "Roboto Slab", "Helvetica", sans-serif;';
css += "  color: #b4d12b;";
css += "  margin-bottom: 20px;";
css += "}";
css += "";
css += "h1 {";
css += "  font-size: 50px;";
css += "  line-height: 55px;";
css += "}";
css += "";
css += "h2 {";
css += "  font-size: 30px;";
css += "  line-height: 38px;";
css += "  color: #879642;";
css += "}";
css += "";
css += "h3 {";
css += "  font-size: 25px;";
css += "  line-height: 30px;";
css += "  color: #f2ffc1;";
css += "}";
css += "";
css += "p {";
css += "  color: #c6c5ac;";
css += '  font-family: "Open Sans", "Helvetica", sans-serif;';
css += "  line-height: 26px;";
css += "  font-size: 15px;";
css += "}";
css += "";
css += "ul {";
css += "}";
css += "";
css += "li {";
css += "  line-height: 26px;";
css += "  font-size: 15px;";
css += "}";
css += "";
css += "a {";
css += "  color: #f2ffc1;";
css += "  text-decoration: none;";
css += "  border-bottom: 1px dashed #e3de8b;";
css += "}";
css += "";
css += "a:hover {";
css += "  color: #c6c5ac;";
css += "  border-bottom: 1px dashed #c6c5ac;";
css += "}";
css += "";

let index = "";
index += "<!DOCTYPE html>";
index += '<html lang="en">';
index += "";
index += "<head>";
index += '    <meta charset="UTF-8">';
index += "    <title>The Elements</title>";
index += '    <link rel="stylesheet" href="/css/styles.css">';
index += "</head>";
index += "";
index += "<body>";
index += "    <h1>The Elements</h1>";
index += "    <h2>These are all the known elements.</h2>";
index += "    <h3>These are 2</h3>";
index += "    <ol>";
index += "        <li>";
index += '            <a href="/assets/hydrogen.html">Hydrogen</a>';
index += "        </li>";
index += "        <li>";
index += '            <a href="/assets/helium.html">Helium</a>';
index += "        </li>";
index += "    </ol>";
index += "</body>";
index += "";
index += "</html>";

let fourOhFour = "";
fourOhFour += "<!DOCTYPE html>";
fourOhFour += '<html lang="en">';
fourOhFour += "";
fourOhFour += "<head>";
fourOhFour += '    <meta charset="UTF-8">';
fourOhFour += "    <title>Element not found!</title>";
fourOhFour += '    <link rel="stylesheet" href="/css/styles.css">';
fourOhFour += "</head>";
fourOhFour += "";
fourOhFour += "<body>";
fourOhFour += "    <h1>404</h1>";
fourOhFour += "    <h2>Element not found!</h2>";
fourOhFour += "    <p>";
fourOhFour += '        <a href="/">back</a>';
fourOhFour += "    </p>";
fourOhFour += "</body>";
fourOhFour += "";
fourOhFour += "</html>";

let hydrogen = "";
hydrogen += "<!DOCTYPE html>";
hydrogen += '<html lang="en">';
hydrogen += "";
hydrogen += "<head>";
hydrogen += '    <meta charset="UTF-8">';
hydrogen += "    <title>The Elements - Hydrogen</title>";
hydrogen += '    <link rel="stylesheet" href="/css/styles.css">';
hydrogen += "</head>";
hydrogen += "";
hydrogen += "<body>";
hydrogen += "    <h1>Hydrogen</h1>";
hydrogen += "    <h2>H</h2>";
hydrogen += "    <h3>Atomic number 1</h3>";
hydrogen +=
  "    <p>Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen";
hydrogen +=
  "        is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in";
hydrogen +=
  "        the universe, constituting roughly 75% of all baryonic mass. Non-remnant stars are mainly composed of hydrogen in";
hydrogen +=
  "        its plasma state. The most common isotope of hydrogen, termed protium (name rarely used, symbol 1H), has a single";
hydrogen += "        proton and zero neutrons.</p>";
hydrogen += "    <p>";
hydrogen += '        <a href="/">back</a>';
hydrogen += "    </p>";
hydrogen += "</body>";
hydrogen += "";
hydrogen += "</html>";

let helium = "";
helium += "<!DOCTYPE html>";
helium += '<html lang="en">';
helium += "";
helium += "<head>";
helium += '    <meta charset="UTF-8">';
helium += "    <title>The Elements - Helium</title>";
helium += '    <link rel="stylesheet" href="/css/styles.css">';
helium += "</head>";
helium += "";
helium += "<body>";
helium += "    <h1>Helium</h1>";
helium += "    <h2>H</h2>";
helium += "    <h3>Atomic number 2</h3>";
helium +=
  "    <p>Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert,";
helium +=
  "        monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest";
helium +=
  "        among all the elements and it exists only as a gas except in extremely cold conditions.</p>";
helium += "    <p>";
helium += '        <a href="/">back</a>';
helium += "    </p>";
helium += "</body>";
helium += "";
helium += "</html>";

module.exports = {
  index,
  css,
  fourOhFour,
  hydrogen,
  helium
};
